#!/usr/bin/env python3
import argparse
import subprocess

PLATFORMS = ["android", "lambda", "native", "wasm"]


def build(platform, version, push):
    image_name = f"canvas-builder-{platform}:{version}"
    tag_name = f"docker.pkg.github.com/vibeus/actions-setup-canvas/canvas-builder-{platform}:{version}"
    subprocess.check_call(["docker", "build", "-t", image_name, platform])
    if push:
        subprocess.check_call(["docker", "tag", image_name, tag_name])
        subprocess.check_call(["docker", "push", tag_name])


def main(args):
    for p in args.platform:
        build(p, args.version, args.push)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="")
    parser.add_argument(
        "-p", "--push", dest="push", action="store_true", help="push to remote"
    )
    parser.add_argument(
        "-v", "--version", dest="version", default="latest", help="image version"
    )
    parser.add_argument(
        "platform", nargs="+", choices=PLATFORMS, help="platform(s) to build"
    )

    args = parser.parse_args()
    main(args)
